# Use the official MySQL image from the Docker Hub
FROM mysql:5.7

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=rootpass
ENV MYSQL_DATABASE=classicmodels

# Add the Classicmodels SQL file to the container
ADD classicmodels.sql /docker-entrypoint-initdb.d/

# Expose the MySQL port
EXPOSE 3306
