# Create a two tier application using docker-compose
# The application consists of a web application and a database
# The web application is a simple flask application that connects to a mysql database
# The database is a mysql database

version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: classicmodels
    ports:
      - "3306:3306"
    volumes:
      - ./classicmodels.sql:/docker-entrypoint-initdb.d/classicmodels.sql
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpass
      MYSQL_DB: classicmodels
