apiVersion: v1
kind: Pod
metadata:
  name: python-app-pod
spec:
  containers:
    - name: mysql
      image: balajich/mysql-db:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpass"
        - name: MYSQL_DATABASE
          value: "classicmodels"
      ports:
        - containerPort: 3306

    - name: python-app
      image: balajich/python-app:latest
      env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "rootpass"
        - name: MYSQL_DB
          value: "classicmodels"
      ports:
        - containerPort: 5000
# expose python-app-pod to the outside world
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  selector:
    app: python-app-pod
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer