# cronjob-def-app4.yml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: print-date-time
spec:
  schedule: "*/10 * * * * "
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: app5-container
              image: balajich/app5:latest
          restartPolicy: OnFailure