apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: app2-daemonset
spec:
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: app2-container
          image: balajich/app2:latest
          command: ["python", "app2.py"]