apiVersion: v1
kind: Pod
metadata:
  name: python-app1-pod
  labels:
    app: python-app1-pod
spec:
  containers:
    - name: python-app1-con
      image: balajich/app1:latest
      ports:
        - containerPort: 5000
    - name: python-app11-con
      image: balajich/app11:latest
      ports:
        - containerPort: 5001
# expose python-app0-pod to the outside world
---
apiVersion: v1
kind: Service
metadata:
  name: python-app1-service
spec:
  selector:
    app: python-app1-pod
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer