# use environment variables to pass the database connection details to the python application
# Access application from minikube using the following command:
# minikube service python-app-service
# Sample URL will be http://127.0.0.1:52598/customers (port number will be different)
apiVersion: v1
kind: Pod
metadata:
  name: python-app-pod
  labels:
    app: python-app-pod
spec:
  containers:
    - name: mysql
      image: balajich/mysql-db:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpass"
        - name: MYSQL_DATABASE
          value: "classicmodels"
      ports:
        - containerPort: 3306

    - name: python-app
      image: balajich/python-app:latest
      env:
        - name: MYSQL_PASSWORD
          value: "rootpass"
        - name: MYSQL_DB
          value: "classicmodels"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_HOST
          value: "localhost"
      ports:
        - containerPort: 5000
# expose python-app-pod to the outside world
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  selector:
    app: python-app-pod
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer